### ISSUE TITLE
Investigate attending.io api

### ISSUE THREAD

**Issue by iancrowther** [barcelona-js/gitup#14]

**Comment by iancrowther** [comment]
I removed the deadline rom the wishlist milestone as its an ongoing concern

**Comment by ifraixedes** [comment]
I got some replies about it, via twitter.

[About it](https://twitter.com/stef/status/553588464185532416)
[A current workaround](https://twitter.com/stef/status/553588655873609729)

**Comment by iancrowther** [comment]
good research - thanks
