### ISSUE TITLE
create Mailchimp module

### ISSUE THREAD

**Issue by iancrowther** [barcelona-js/gitup#17]
Automate newsletter inc talks, twitter / github handles.

**Comment by iancrowther** [comment]
newsletter template could be a gist

**Comment by ifraixedes** [comment]
If the provider is Mailchimp, we have to use Mandril; managing with a gist I don't know exactly now if it can be tricky than having the template in other place.

By the way, the official npm module for Mandril is quite crap implementation, however I guess that it works.

**Comment by iancrowther** [comment]
thanks, the gist gives us a template + editor in GH, but it can be a *.MD file in the repo too

**Comment by ifraixedes** [comment]
Sure, we are in brainstorming mode.

**Comment by iancrowther** [comment]
see https://github.com/barcelona-js/gitup/issues/5

**Comment by PatrickHeneise** [comment]
#5 is more general.
