### ISSUE TITLE
Trigger a GitHub pages build

### ISSUE THREAD

**Issue by PatrickHeneise** [barcelona-js/gitup#22]
The data coming in from a Webhook should be processed; uploaded and committed to GitHub in the gh-pages branch to get an updated website.

**Comment by iancrowther** [comment]
+1

**Comment by ifraixedes** [comment]
+1 because it'd automatise updating tasks. As humans are very error prone to introduce errors in repetitive tasks, moreover when we have to do in small gaps of free time

**Comment by iancrowther** [comment]
harpjs is the way fwd here IMO

**Comment by ifraixedes** [comment]
@iancrowther  I took a quick look a few months ago, I liked as static site generator, let's see other proposals to compare and make a decision

**Comment by PatrickHeneise** [comment]
Instead of building the whole page every time, there's also an approach to use the GitHub issues API and just build a static site with AJAX calls: https://github.com/drpicox/proto-githubmeetup

**Comment by PatrickHeneise** [comment]
Will be done like this then: https://github.com/drpicox/proto-githubmeetup
