### ISSUE TITLE
Integrate GitHub API

### ISSUE THREAD

**Issue by PatrickHeneise** [barcelona-js/gitup#4]
I'm looking into the GitHub API and it seems it's possible to upload a blob, create a tree and then commit the file into the repository. This way a JSON file could be created that holds the event information.

https://developer.github.com/v3/git/blobs/
https://developer.github.com/v3/git/trees/

This seems a bit cumbersome, suggestions to improve?

**Comment by steffen** [comment]
Not too sure about the overall requirement, but using gists could be an alternative, would basically make out of three steps (upload a blob, create a tree and then commit) one step:
https://developer.github.com/v3/gists/#create-a-gist

**Comment by PatrickHeneise** [comment]
I think with gists it's loosing the context to the group. Should all be in the repo.

**Comment by iancrowther** [comment]
tbf - i agree, gists are tied to individuals.. nice thought tho

**Comment by iancrowther** [comment]
@PatrickHeneise - this has been superseded now.. close?
